export const MESSAGE_EVENT_TYPES = {
    HTML_RESPONSE: 'HTML_RESPONSE',
    GET_HTML: 'GET_HTML',
    HIGHLIGHT_ELEMENT: 'HIGHLIGHT_ELEMENT',
    NAVIGATION_EVENT: 'NAVIGATION_EVENT',
    GET_HTML_RESPONSE: 'GET_HTML_RESPONSE',
    CHATBOT_READY: 'CHATBOT_READY',
    CLEAR_HIGHLIGHT: 'CLEAR_HIGHLIGHT',
    NOTIFY_OF_COMPLETION: 'NOTIFY_OF_COMPLETION',
    REQUEST_INIT: 'REQUEST_INIT',
    INITIALIZE: 'INITIALIZE',
} as const;

export type MessageEventType = typeof MESSAGE_EVENT_TYPES[keyof typeof MESSAGE_EVENT_TYPES];